# Generated by Django 4.1.7 on 2023-03-26 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=30)),
                ('content', models.TextField()),
            ],
        ),
    ]
